language: generic
sudo: required
service:
  - docker


before_install:
  - docker build -t ashwinikumarmishra/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ashwinikumarmishra/docker-react npm run test
